# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6e84a4dfec6c54cba4c34664c401bca13f69b9b20b8c116f32859256f98628a73864d399761a9a9181f67d0c8bd01b61c05587960deb51a5ece6bfe51770a63

test:
  secret_key_base: 782ccaf48fa273f8457dffbccba08b7d12d3c4d2425070dadfe22e28e1d8d173a8bd25807a9b3a34330d7854f41531bc0a5ab9b775f0bf80f59f92f41f562174

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
